name: TheHarveyCodyChronicles
favicon: null
layout_spectrum: 0.8139906816650182
typography_spectrum: 0.8654213780537248
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0100'
    - '#fffefc'
    - '#75513b'
    - '#be9b7d'
    - '#e2d8cc'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
