name: TheHarveyCodyChronicles
favicon: null
layout_spectrum: 0.8139906816650182
typography_spectrum: 0.8654213780537248
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.000571616692468524
  lightness: 0.557789399754256
  saturation: 0.406084839720279
  rhythmicContrast: 0.49471698398701847
purpose: []
